[global]
# Global configuration
developmentMode = false
showWarningOnDirectExecution = false

[server]
# Server configuration
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
# Browser configuration
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[theme]
primaryColor = "#00d4ff"          # Bright cyan
backgroundColor = "#0e1117"       # Dark background
secondaryBackgroundColor = "#1e2936"
textColor = "#ffffff"

[client]
# Client configuration
showErrorDetails = true
toolbarMode = "auto"

[runner]
# Runner configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
# Logger configuration
level = "info"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
# Deprecation warnings
showPyplotGlobalUse = false
